theme: jekyll-theme-minimal
title: Nina Fischer
# logo: 
description: Statistician. Previously working on the calibration and uncertainty quantification for large scale computer models, with a focus on crop and carbon cycle computer models. Now, I work on communicating uncertainty quantification for flood modelling. 
