theme: jekyll-theme-minimal
title: Nina Fischer's homepage
description: Final-year Statistics PhD student, working on the calibration and uncertainty quantification for large scale computer models, with a focus on crop and carbon cycle computer models. 
